# This workflow lints the source code
name: Lint Code

# Controls when this workflow will run.
on:
  # Allows you to call this workflow from other workflows
  workflow_call:
    secrets:
      depotTokenReadOnly:
        required: true

  # Allows you to tun this workflow manually from the Actions tab
  workflow_dispatch: {}

# Cancel running workflows (this replaces the old cancel-workflow.yml script)
concurrency:
  group: lint-code-group
  cancel-in-progress: true

jobs:
  lint-code:
    name: "🕵️‍♂️ Lint Code"
    runs-on: ubuntu-latest
    steps:
      - name: "☁️ Checkout repository"
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: false

      - name: "⚙️ Use Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          check-latest: true
          cache: "npm"

      - name: "⚙️ Setup Mitel depot"
        env:
          depotToken: ${{ secrets.depotTokenReadOnly  }}
          depot: depot.mitel.io/artifactory/api/npm/npm-internal/
        run: |
          npm config set @mitel-internal:registry 'https://${{ env.depot }}'
          npm config set '//${{ env.depot }}:_authToken=${{ env.depotToken }}'

      - name: "⛓️ Install dependencies"
        run: npm ci --audit=false --prefer-offline --progress=false

      - name: "✅ Lint code"
        run: npm run lint

      - name: "🧹 Cleanup workspace"
        run: |
          echo "🧹 Cleaning working directory..."
          rm -rf ./*
